# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/framework-stablediff',
                'doc_host': 'https://ersanjeevkm.github.io',
                'git_url': 'https://github.com/ersanjeevkm/framework-stablediff',
                'lib_path': 'framework_stablediff'},
  'syms': {'framework_stablediff.core': {'framework_stablediff.core.foo': ('core.html#foo', 'framework_stablediff/core.py')}}}
